#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${DB_USER}
        LOGIN
        PASSWORD '${DB_PASSWORD}';

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DB_USER};
    GRANT USAGE ON SCHEMA public TO ${DB_USER};
EOSQL